<a href="https://colab.research.google.com/github/Ilieska/VNP/blob/main/Diplomska_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (2024.8.30)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 3.8 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [2]:
import pandas as pd
import numpy as np
import csv
from google.colab import drive
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import requests
from bs4 import BeautifulSoup
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [3]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
data = pd.read_csv('/content/drive/MyDrive/VNP-PROEKT/20240924210000.export.CSV',header=None, sep='\t')

In [5]:
data.columns = [
    'GlobalEventID', 'Day', 'MonthYear', 'Year', 'FractionDate', 'Actor1Code',
    'Actor1Name', 'Country Code', 'Actor1KnownGroupCode', 'Actor1EthnicCode',
    'Actor1Religion1Code', 'Actor1Religion2Code', 'Actor1Type1Code', 'Actor1Type2Code',
    'Actor1Type3Code', 'Actor2Code', 'Actor2Name', 'Actor2CountryCode', 'Actor2KnownGroupCode',
    'Actor2EthnicCode', 'Actor2Religion1Code', 'Actor2Religion2Code', 'Actor2Type1Code',
    'Actor2Type2Code', 'Actor2Type3Code', 'IsRootEvent', 'EventCode', 'EventBaseCode',
    'EventRootCode', 'QuadClass', 'GoldsteinScale', 'NumMentions', 'NumSources', 'NumArticles',
    'AvgTone', 'Actor1Geo_Type', 'Actor1Geo_FullName', 'Actor1Geo_CountryCode', 'Actor1Geo_ADM1Code',
    'Actor1Geo_ADM2Code', 'Actor1Geo_Lat', 'Actor1Geo_Long', 'Actor1Geo_FeatureID',
    'Actor2Geo_Type', 'Actor2Geo_FullName', 'Actor2Geo_CountryCode', 'Actor2Geo_ADM1Code',
    'Actor2Geo_ADM2Code', 'Actor2Geo_Lat', 'Actor2Geo_Long', 'Actor2Geo_FeatureID',
    'ActionGeo_Type', 'ActionGeo_FullName', 'ActionGeo_CountryCode', 'ActionGeo_ADM1Code',
    'ActionGeo_ADM2Code', 'ActionGeo_Lat', 'ActionGeo_Long', 'ActionGeo_FeatureID',
    'DATEADDED', 'SOURCEURL'
]

In [6]:
data.head(10)

,GlobalEventID,Day,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Country Code,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
0,1200179223,20230925,202309,2023,2023.7260,NaN,NaN,NaN,NaN,NaN,...,3,"Decatur, New York, United States",US,USNY,NY077,42.644200,-74.7252,948156,20240924210000,https://www.ajc.com/food-and-dining/two-atlant...
1,1200179224,20230925,202309,2023,2023.7260,NaN,NaN,NaN,NaN,NaN,...,4,"Maseno, Nyanza, Kenya",KE,KE07,18585,-0.004165,34.6095,-2255306,20240924210000,https://www.mccormick.northwestern.edu/news/ar...
2,1200179225,20230925,202309,2023,2023.7260,BUS,BUSINESS,NaN,NaN,NaN,...,3,"Glenwood Park, New York, United States",US,USNY,NaN,41.513400,-74.0499,951254,20240924210000,https://www.ajc.com/food-and-dining/two-atlant...
3,1200179226,20230925,202309,2023,2023.7260,BUS,BUSINESS,NaN,NaN,NaN,...,3,"Glenwood Park, New York, United States",US,USNY,NaN,41.513400,-74.0499,951254,20240924210000,https://www.ajc.com/food-and-dining/two-atlant...
4,1200179227,20230925,202309,2023,2023.7260,GOV,ADMINISTRATION,NaN,NaN,NaN,...,3,"Times Square, New York, United States",US,USNY,NaN,40.757000,-73.9860,967537,20240924210000,https://www.ajc.com/news/atlanta-news/city-of-...
5,1200179228,20230925,202309,2023,2023.7260,JEW,JEWISH,NaN,NaN,NaN,...,4,"Gaza, Israel (general), Israel",IS,IS00,18315,31.416700,34.3333,-797156,20240924210000,https://www.cbc.ca/news/politics/palestinian-s...
6,1200179229,20230925,202309,2023,2023.7260,KEN,KENYA,KEN,NaN,NaN,...,4,"Maseno, Nyanza, Kenya",KE,KE07,18585,-0.004165,34.6095,-2255306,20240924210000,https://www.mccormick.northwestern.edu/news/ar...
7,1200179230,20230925,202309,2023,2023.7260,USA,UNITED STATES,USA,NaN,NaN,...,3,"Decatur, New York, United States",US,USNY,NY077,42.644200,-74.7252,948156,20240924210000,https://www.ajc.com/food-and-dining/two-atlant...
8,1200179231,20230925,202309,2023,2023.7260,USAMIL,THE US,USA,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20240924210000,https://www.yahoo.com/news/oceangate-titan-imp...
9,1200179232,20240825,202408,2024,2024.6438,GOV,ADMINISTRATION,NaN,NaN,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,DC001,38.895100,-77.0364,531871,20240924210000,https://www.aljazeera.com/news/2024/9/24/disas...

In [7]:
print(data['SOURCEURL'])

0       https://www.ajc.com/food-and-dining/two-atlant...
1       https://www.mccormick.northwestern.edu/news/ar...
2       https://www.ajc.com/food-and-dining/two-atlant...
3       https://www.ajc.com/food-and-dining/two-atlant...
4       https://www.ajc.com/news/atlanta-news/city-of-...
                              ...
1452    https://www.aljazeera.com/program/newsfeed/202...
1453    https://news.emory.edu/stories/2024/09/er_scie...
1454    https://news.emory.edu/stories/2024/09/er_scie...
1455    https://www.yahoo.com/news/coroner-seeks-help-...
1456    https://arktimes.com/rock-candy/2024/09/24/fiv...
Name: SOURCEURL, Length: 1457, dtype: object

In [8]:
actor1_counts = data['Country Code'].value_counts()

In [9]:
pd.set_option('display.max_rows', None)

In [10]:
print(actor1_counts)

Country Code
USA    359
CAN     43
ISR     37
GBR     28
LBN     21
NGA     20
AFR     15
RUS     14
QAT     14
PSE     14
ITA     13
SYR     13
HTI     13
BGD     13
CHN     12
MEX     10
IRN     10
PAK     10
GHA      8
IRQ      8
ZAF      8
NLD      8
TUR      8
COL      7
EUR      6
FRA      6
BTN      6
SGP      6
UKR      6
SAU      5
JPN      5
UGA      4
KEN      4
IRL      4
HUN      4
EGY      4
DEU      4
IDN      3
KHM      3
GRC      3
LIE      3
SOM      3
PRT      3
ARE      2
AUS      2
BEL      2
CHE      2
CMR      2
IND      2
DZA      2
JOR      2
PHL      2
CRI      1
NZL      1
DNK      1
BRB      1
BFA      1
MLI      1
LAO      1
THA      1
GTM      1
AFG      1
YEM      1
Name: count, dtype: int64

In [11]:
countries_of_interest = ['CAN', 'RUS']

# Step 2: Filter the dataset for these countries
filtered_df = data[data['Country Code'].isin(countries_of_interest)]

# Step 3: Remove duplicate URLs
filtered_df_unique = filtered_df.drop_duplicates(subset=['SOURCEURL'])

# Step 4: Ensure full URLs are displayed
pd.set_option('display.max_colwidth', None)

# Step 5: Print the filtered and deduplicated DataFrame
print("Source URLs for selected countries:")
print(filtered_df_unique[['Country Code', 'SOURCEURL']])

Source URLs for selected countries:
     Country Code  \
30            CAN
261           CAN
262           CAN
263           CAN
264           CAN
266           CAN
267           CAN
268           CAN
270           CAN
273           CAN
274           CAN
277           CAN
280           CAN
298           CAN
920           CAN
1022          RUS
1024          RUS
1028          RUS
1029          RUS
1032          RUS

                                                                                                                                                                                           SOURCEURL
30                                                                                                                   https://www.producer.com/news/port-of-vancouver-grain-workers-walk-off-the-job/
261                                                                                                                                                       https://boom1019.com/a-day-to-listen-2024/
262                                                                                                                  https://www.cbc.ca/news/politics/palestinian-state-israel-gaza-canada-1.7332692
263                                                                                                                  https://www.cbc.ca/news/canada/manitoba/zebra-mussels-more-clear-lake-1.7332643
264                                                                                          https://www.nme.com/news/film/elizabeth-olsen-remembers-being-starstruck-meeting-george-clooney-3796710
266                                                                                          https://winnipeg.ctvnews.ca/multiple-juvenile-zebra-mussels-found-in-cleark-lake-parks-canada-1.7050203
267                                                                                          https://fftimes.com/news/district-news/thousands-march-in-toronto-to-demand-justice-for-grassy-narrows/
268                                                                                                            https://vancouversun.com:443/news/bc-judge-orders-home-returned-to-victim-elder-abuse
270                                             https://www.cbc.ca/news/canada/edmonton/1-person-injured-as-valley-line-train-derails-in-collision-with-semi-trailer-in-southeast-edmonton-1.7332475
273                                                                                                                                        https://www.spacedaily.com/afp/240924171607.5477bitu.html
274                                                                           https://toronto.ctvnews.ca/toronto-driver-who-allegedly-struck-and-killed-26-year-old-cyclist-charged-police-1.7050094
277                                           https://www.winnipegfreepress.com/arts-and-life/life/health/2024/09/24/liberals-launch-pandemic-preparedness-agency-seeking-faster-vaccine-development
280                                                                         https://fftimes.com/news/district-news/clean-water-for-first-nations-needed-before-next-elections-house-committee-hears/
298                                                                                                   https://www.cbc.ca/news/canada/manitoba/manitoba-breast-cancer-screening-age-lowered-1.7332402
920                                                                                    https://www.thegrocer.co.uk/comment-and-opinion/panoramas-price-match-probe-is-misleading-tosh/695857.article
1022                                                                                                         https://www.theguardian.com/world/2024/sep/24/zelenskyy-united-nations-security-council
1024                                                                                                                                                https://www.eurekalert.org/news-releases/1059133
1028                                                                                https://www.channelnewsasia.com/world/united-nations-biden-ukraine-general-assemmbly-israel-iran-lebanon-4630821
1029                                                                                                                        https://www.producer.com/news/red-lentil-crops-might-be-getting-smaller/
1032  https://www.marketscreener.com/quote/currency/US-DOLLAR-RUSSIAN-ROUBLE--2370597/news/Exclusive-Iran-brokering-talks-to-send-advanced-Russian-missiles-to-Yemen-s-Houthis-sources-say-47931028/

analiza
sentiment

In [ ]:
url = filtered_df_unique['SOURCEURL']

def get_text_from_url(url):
    """Fetch and extract text content from a URL."""
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, 'html.parser')
        paragraphs = soup.find_all('p')
        text = ' '.join(para.get_text() for para in paragraphs)
        return text
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return ""

def analyze_sentiment(text):
    """Perform sentiment analysis using VADER."""
    analyzer = SentimentIntensityAnalyzer()
    sentiment_score = analyzer.polarity_scores(text)
    return sentiment_score

# Analyze sentiment for each unique URL
sentiment_results = []
for _, row in filtered_df_unique.iterrows():
    url = row['SOURCEURL']
    country = row['Country Code']
    print(f"Processing URL: {url}")

    # Extract text from URL
    text = get_text_from_url(url)

    # Perform sentiment analysis
    sentiment = analyze_sentiment(text)

    # Store the results
    sentiment_results.append({
        'Country Code': country,
        'SOURCEURL': url,
        'Sentiment': sentiment
    })

# Create a DataFrame for sentiment results
sentiment_df = pd.DataFrame(sentiment_results)

# Print sentiment results
print("\nSentiment Analysis Results:")
print(sentiment_df)

Processing URL: https://www.producer.com/news/port-of-vancouver-grain-workers-walk-off-the-job/
Processing URL: https://boom1019.com/a-day-to-listen-2024/
Processing URL: https://www.cbc.ca/news/politics/palestinian-state-israel-gaza-canada-1.7332692